# Build stage
FROM eclipse-temurin:21-jdk-alpine as build
WORKDIR /workspace/app

# Copy the Maven wrapper and the project files
COPY mvnw .
COPY .mvn/ .mvn/
COPY pom.xml .
COPY src src

# Make the mvnw script executable
RUN chmod +x ./mvnw

# Build the application
RUN ./mvnw clean install -DskipTests

# Runtime stage
FROM eclipse-temurin:21-jre-alpine
VOLUME /tmp

# Copy the JAR file from the build stage
ARG DEPENDENCY=/workspace/app/target
COPY --from=build ${DEPENDENCY}/*.jar app.jar

# Run the Spring Boot app
ENTRYPOINT ["java", "-jar", "/app.jar"]
